//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteka1.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfKsiazkaDoBazy4")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ksiazka", Namespace="http://schemas.datacontract.org/2004/07/WcfKsiazkaDoBazy4")]
    [System.SerializableAttribute()]
    public partial class Ksiazka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataWypozyczeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataZwrotuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iloscStronField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imieAutoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int licznikPrzedluzenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int licznikWypozyczenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwiskoAutoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Queue<int> rezerwacjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rodzajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool stanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tytulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataWypozyczenia {
            get {
                return this.dataWypozyczeniaField;
            }
            set {
                if ((this.dataWypozyczeniaField.Equals(value) != true)) {
                    this.dataWypozyczeniaField = value;
                    this.RaisePropertyChanged("dataWypozyczenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataZwrotu {
            get {
                return this.dataZwrotuField;
            }
            set {
                if ((this.dataZwrotuField.Equals(value) != true)) {
                    this.dataZwrotuField = value;
                    this.RaisePropertyChanged("dataZwrotu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iloscStron {
            get {
                return this.iloscStronField;
            }
            set {
                if ((this.iloscStronField.Equals(value) != true)) {
                    this.iloscStronField = value;
                    this.RaisePropertyChanged("iloscStron");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imieAutora {
            get {
                return this.imieAutoraField;
            }
            set {
                if ((object.ReferenceEquals(this.imieAutoraField, value) != true)) {
                    this.imieAutoraField = value;
                    this.RaisePropertyChanged("imieAutora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int licznikPrzedluzen {
            get {
                return this.licznikPrzedluzenField;
            }
            set {
                if ((this.licznikPrzedluzenField.Equals(value) != true)) {
                    this.licznikPrzedluzenField = value;
                    this.RaisePropertyChanged("licznikPrzedluzen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int licznikWypozyczen {
            get {
                return this.licznikWypozyczenField;
            }
            set {
                if ((this.licznikWypozyczenField.Equals(value) != true)) {
                    this.licznikWypozyczenField = value;
                    this.RaisePropertyChanged("licznikWypozyczen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazwiskoAutora {
            get {
                return this.nazwiskoAutoraField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwiskoAutoraField, value) != true)) {
                    this.nazwiskoAutoraField = value;
                    this.RaisePropertyChanged("nazwiskoAutora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrISBN {
            get {
                return this.nrISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.nrISBNField, value) != true)) {
                    this.nrISBNField = value;
                    this.RaisePropertyChanged("nrISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Queue<int> rezerwacje {
            get {
                return this.rezerwacjeField;
            }
            set {
                if ((object.ReferenceEquals(this.rezerwacjeField, value) != true)) {
                    this.rezerwacjeField = value;
                    this.RaisePropertyChanged("rezerwacje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rodzaj {
            get {
                return this.rodzajField;
            }
            set {
                if ((object.ReferenceEquals(this.rodzajField, value) != true)) {
                    this.rodzajField = value;
                    this.RaisePropertyChanged("rodzaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool stan {
            get {
                return this.stanField;
            }
            set {
                if ((this.stanField.Equals(value) != true)) {
                    this.stanField = value;
                    this.RaisePropertyChanged("stan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tytul {
            get {
                return this.tytulField;
            }
            set {
                if ((object.ReferenceEquals(this.tytulField, value) != true)) {
                    this.tytulField = value;
                    this.RaisePropertyChanged("tytul");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        biblioteka1.ServiceReference4.CompositeType GetDataUsingDataContract(biblioteka1.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<biblioteka1.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(biblioteka1.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertKsiazka", ReplyAction="http://tempuri.org/IService1/InsertKsiazkaResponse")]
        int InsertKsiazka(biblioteka1.ServiceReference4.Ksiazka k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertKsiazka", ReplyAction="http://tempuri.org/IService1/InsertKsiazkaResponse")]
        System.Threading.Tasks.Task<int> InsertKsiazkaAsync(biblioteka1.ServiceReference4.Ksiazka k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : biblioteka1.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<biblioteka1.ServiceReference4.IService1>, biblioteka1.ServiceReference4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public biblioteka1.ServiceReference4.CompositeType GetDataUsingDataContract(biblioteka1.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<biblioteka1.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(biblioteka1.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int InsertKsiazka(biblioteka1.ServiceReference4.Ksiazka k) {
            return base.Channel.InsertKsiazka(k);
        }
        
        public System.Threading.Tasks.Task<int> InsertKsiazkaAsync(biblioteka1.ServiceReference4.Ksiazka k) {
            return base.Channel.InsertKsiazkaAsync(k);
        }
    }
}
